# Gopkg.toml
#
# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.

[[constraint]]
  branch = "master"
  name = "github.com/antchfx/xmlquery"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.15.57"

[[constraint]]
  name = "github.com/go-ini/ini"
  version = "1.39.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.2.1"

[[constraint]]
  branch = "master"
  name = "github.com/vinhjaxt/persistent-cookiejar"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[prune]
  go-tests = true
  unused-packages = true
